package com.revealprecision.revealserver.persistence.repository;

import com.cosium.spring.data.jpa.entity.graph.repository.EntityGraphJpaRepository;
import com.revealprecision.revealserver.persistence.domain.HdssCompounds;
import com.revealprecision.revealserver.persistence.projection.HdssCompoundHouseholdIndividualProjection;
import com.revealprecision.revealserver.persistence.projection.HdssIndividualProjection;
import java.util.List;
import java.util.UUID;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

@Repository
public interface HdssCompoundsRepository extends EntityGraphJpaRepository<HdssCompounds, UUID> {

  @Query(value = "SELECT nextval('hdss.hdss_compounds_seq')", nativeQuery = true)
  long getNextServerVersion();


//  @Query(value = "SELECT DISTINCT "
//      + " cast(hc.id as varchar) as id, hc.compound_id as compoundId,hc.household_id as householdId,hc.individual_id as individualId, "
//      + " hc.fields->>'gender' as gender, CAST(hc.fields->>'dob' as date)  as dob, hc.server_version as serverVersion"
//      + ", cast(hc.structure_id as varchar) as structureId ,hc.name as name"
//      + ", cast(hc.floating_location_id as varchar) as getFloatingLocationId "
//      + ", cast(hc.floating_location_name as varchar) as getFloatingLocationName "
//      + ", cast(hc.floating_location_geographic_level as varchar) as getFloatingLocationGeographicLevel "
//      + " FROM\n"
//      + "(SELECT lr.location_identifier as child_location, arr.ancestor\n"
//      + "from location_relationship lr,\n"
//      + "     unnest(lr.ancestry) with ordinality arr(ancestor, pos)\n"
//      + "    ) as lr\n"
//      + "left join location lp on lr.ancestor = lp.identifier\n"
//      + "left join geographic_level pgl on pgl.identifier = lp.geographic_level_identifier\n"
//      + "left join location lc on lc.identifier = lr.child_location\n"
//      + "left join geographic_level cgl on cgl.identifier = lc.geographic_level_identifier\n"
//      + "inner  join hdss.hdss_compounds hc on hc.structure_id = lr.child_location \n"
//      + "WHERE lp.identifier in (\n"
//      + "    SELECT\n"
//      + "           l.identifier\n"
//      + "    from plan_assignment pa\n"
//      + "             inner join organization o on pa.organization_identifier = o.identifier\n"
//      + "             left join plan_locations pl on pl.identifier = pa.plan_locations_identifier\n"
//      + "             left join location l on l.identifier = pl.location_identifier\n"
//      + "             left join geographic_level gl on gl.identifier = l.geographic_level_identifier\n"
//      + "             left join plan p on pl.plan_identifier = p.identifier\n"
//      + "             left join location_hierarchy lh on p.hierarchy_identifier = lh.identifier\n"
//      + "             left join plan_target_type ptt on ptt.plan_identifier = p.identifier\n"
//      + "             left join geographic_level pgl on ptt.geographic_level_identifier = pgl.identifier\n"
//      + "             left join user_organization uo on o.identifier = uo.organization_identifier\n"
//      + "             left join users u on u.identifier = uo.user_identifier\n"
//      + "    WHERE gl.name = lh.node_order[array_position(lh.node_order, pgl.name) - 1]\n"
//      + "      and u.username = :username\n "
//      + "    ) and  hc.server_version>:serverVersion order by hc.server_version LIMIT :batchSize",nativeQuery = true)
//  List<HdssCompoundHouseholdIndividualProjection> getAllCompoundsForUserAssignmentAndServerVersionAndBatchSize(String username, long serverVersion, int batchSize);



  @Query(value = "SELECT DISTINCT cast(hc.id as varchar)                                 as id,\n"
      + "                hc.compound_id                                         as compoundId,\n"
      + "                hc.household_id                                        as householdId,\n"
      + "                hc.individual_id                                       as individualId,\n"
      + "                lp.name                                                as cluster,\n"
      + "                hc.fields ->> 'gender'                                 as gender,\n"
      + "                CAST(hc.fields ->> 'dob' as date)                      as dob,\n"
      + "                hc.server_version                                      as serverVersion,\n"
      + "                cast(hc.structure_id as varchar)                       as structureId,\n"
      + "                hc.name                                                as name,\n"
      + "                cast(hc.floating_location_id as varchar)               as floatingLocationId,\n"
      + "                cast(hc.floating_location_name as varchar)             as floatingLocationName,\n"
      + "                cast(hc.floating_location_geographic_level as varchar) as floatingLocationGeographicLevel,\n"
      + "                cast(hc.floating_household_location_name as varchar)             as floatingHouseholdLocationName\n"
      + "FROM hdss.hdss_compounds hc\n"
      + "         LEFT JOIN\n"
      + "\n"
      + "     (SELECT lr.location_identifier as child_location, arr.ancestor\n"
      + "      from location_relationship lr,\n"
      + "           unnest(lr.ancestry) with ordinality arr(ancestor, pos)\n"
      + "     ) as lr on lr.child_location = hc.structure_id\n"
      + "         left join location lp on lr.ancestor = lp.identifier\n"
      + "\n"
      + "WHERE (lr.ancestor in (\n"
      + "    SELECT l.identifier\n"
      + "    from plan_assignment pa\n"
      + "             inner join organization o on pa.organization_identifier = o.identifier\n"
      + "             left join plan_locations pl on pl.identifier = pa.plan_locations_identifier\n"
      + "             left join location l on l.identifier = pl.location_identifier\n"
      + "             left join geographic_level gl on gl.identifier = l.geographic_level_identifier\n"
      + "             left join plan p on pl.plan_identifier = p.identifier\n"
      + "             left join location_hierarchy lh on p.hierarchy_identifier = lh.identifier\n"
      + "             left join plan_target_type ptt on ptt.plan_identifier = p.identifier\n"
      + "             left join geographic_level pgl on ptt.geographic_level_identifier = pgl.identifier\n"
      + "             left join user_organization uo on o.identifier = uo.organization_identifier\n"
      + "             left join users u on u.identifier = uo.user_identifier\n"
      + "    WHERE gl.name = lh.node_order[array_position(lh.node_order, pgl.name) - 1]\n"
      + "      and u.username = :username\n"
      + ") or hc.floating_location_name in (SELECT l.name\n"
      + "                                   from plan_assignment pa\n"
      + "                                            inner join organization o on pa.organization_identifier = o.identifier\n"
      + "                                            left join plan_locations pl\n"
      + "                                                      on pl.identifier = pa.plan_locations_identifier\n"
      + "                                            left join location l on l.identifier = pl.location_identifier\n"
      + "                                            left join geographic_level gl\n"
      + "                                                      on gl.identifier = l.geographic_level_identifier\n"
      + "                                            left join plan p on pl.plan_identifier = p.identifier\n"
      + "                                            left join location_hierarchy lh\n"
      + "                                                      on p.hierarchy_identifier = lh.identifier\n"
      + "                                            left join plan_target_type ptt on ptt.plan_identifier = p.identifier\n"
      + "                                            left join geographic_level pgl\n"
      + "                                                      on ptt.geographic_level_identifier = pgl.identifier\n"
      + "                                            left join user_organization uo\n"
      + "                                                      on o.identifier = uo.organization_identifier\n"
      + "                                            left join users u on u.identifier = uo.user_identifier\n"
      + "                                   WHERE gl.name =\n"
      + "                                         lh.node_order[array_position(lh.node_order, pgl.name) - 1]\n"
      + "                                     and u.username = :username"
      + ") or hc.floating_household_location_name  in (SELECT l.name\n"
      + "                                   from plan_assignment pa\n"
      + "                                            inner join organization o on pa.organization_identifier = o.identifier\n"
      + "                                            left join plan_locations pl\n"
      + "                                                      on pl.identifier = pa.plan_locations_identifier\n"
      + "                                            left join location l on l.identifier = pl.location_identifier\n"
      + "                                            left join geographic_level gl\n"
      + "                                                      on gl.identifier = l.geographic_level_identifier\n"
      + "                                            left join plan p on pl.plan_identifier = p.identifier\n"
      + "                                            left join location_hierarchy lh\n"
      + "                                                      on p.hierarchy_identifier = lh.identifier\n"
      + "                                            left join plan_target_type ptt on ptt.plan_identifier = p.identifier\n"
      + "                                            left join geographic_level pgl\n"
      + "                                                      on ptt.geographic_level_identifier = pgl.identifier\n"
      + "                                            left join user_organization uo\n"
      + "                                                      on o.identifier = uo.organization_identifier\n"
      + "                                            left join users u on u.identifier = uo.user_identifier\n"
      + "                                   WHERE gl.name =\n"
      + "                                         lh.node_order[array_position(lh.node_order, pgl.name) - 1]\n"
      + "                                     and u.username = :username"
      + ")"
      + ")\n"
      + "  and hc.server_version > :serverVersion\n"
      + "order by hc.server_version\n"
      + "\n"
      + "LIMIT :batchSize",nativeQuery = true)
  List<HdssCompoundHouseholdIndividualProjection> getAllCompoundsForUserAssignmentAndServerVersionAndBatchSize(String username, long serverVersion, int batchSize);

  @Query(value = "SELECT DISTINCT cast(hc.id as varchar)                                 as id,\n"
      + "                hc.compound_id                                         as compoundId,\n"
      + "                hc.household_id                                        as householdId,\n"
      + "                hc.individual_id                                       as individualId,\n"
      + "                lp.name                                                as cluster,\n"
      + "                hc.fields ->> 'gender'                                 as gender,\n"
      + "                CAST(hc.fields ->> 'dob' as date)                      as dob,\n"
      + "                hc.server_version                                      as serverVersion,\n"
      + "                cast(hc.structure_id as varchar)                       as structureId,\n"
      + "                hc.name                                                as name,\n"
      + "                cast(hc.floating_location_id as varchar)               as floatingLocationId,\n"
      + "                cast(hc.floating_location_name as varchar)             as floatingLocationName,\n"
      + "                cast(hc.floating_location_geographic_level as varchar) as floatingLocationGeographicLevel,\n"
      + "                cast(hc.floating_household_location_name as varchar)             as floatingHouseholdLocationName\n"
      + "FROM hdss.hdss_compounds hc\n"
      + "         LEFT JOIN\n"
      + "\n"
      + "     (SELECT lr.location_identifier as child_location, arr.ancestor\n"
      + "      from location_relationship lr,\n"
      + "           unnest(lr.ancestry) with ordinality arr(ancestor, pos)\n"
      + "     ) as lr on lr.child_location = hc.structure_id\n"
      + "         left join location lp on lr.ancestor = lp.identifier\n"
      + "\n"
      + "WHERE (cast(lr.ancestor as varchar) in (\n"
      + "    SELECT cast(l.identifier as varchar)\n"
      + "    from plan_assignment pa\n"
      + "             inner join organization o on pa.organization_identifier = o.identifier\n"
      + "             left join plan_locations pl on pl.identifier = pa.plan_locations_identifier\n"
      + "             left join location l on l.identifier = pl.location_identifier\n"
      + "             left join geographic_level gl on gl.identifier = l.geographic_level_identifier\n"
      + "             left join plan p on pl.plan_identifier = p.identifier\n"
      + "             left join location_hierarchy lh on p.hierarchy_identifier = lh.identifier\n"
      + "             left join plan_target_type ptt on ptt.plan_identifier = p.identifier\n"
      + "             left join geographic_level pgl on ptt.geographic_level_identifier = pgl.identifier\n"
      + "             left join user_organization uo on o.identifier = uo.organization_identifier\n"
      + "             left join users u on u.identifier = uo.user_identifier\n"
      + "    WHERE gl.name = lh.node_order[array_position(lh.node_order, pgl.name) - 1]\n"
      + "      and u.username = :username\n"
      + ") or hc.floating_location_name in (SELECT l.name\n"
      + "                                   from plan_assignment pa\n"
      + "                                            inner join organization o on pa.organization_identifier = o.identifier\n"
      + "                                            left join plan_locations pl\n"
      + "                                                      on pl.identifier = pa.plan_locations_identifier\n"
      + "                                            left join location l on l.identifier = pl.location_identifier\n"
      + "                                            left join geographic_level gl\n"
      + "                                                      on gl.identifier = l.geographic_level_identifier\n"
      + "                                            left join plan p on pl.plan_identifier = p.identifier\n"
      + "                                            left join location_hierarchy lh\n"
      + "                                                      on p.hierarchy_identifier = lh.identifier\n"
      + "                                            left join plan_target_type ptt on ptt.plan_identifier = p.identifier\n"
      + "                                            left join geographic_level pgl\n"
      + "                                                      on ptt.geographic_level_identifier = pgl.identifier\n"
      + "                                            left join user_organization uo\n"
      + "                                                      on o.identifier = uo.organization_identifier\n"
      + "                                            left join users u on u.identifier = uo.user_identifier\n"
      + "                                   WHERE gl.name =\n"
      + "                                         lh.node_order[array_position(lh.node_order, pgl.name) - 1]\n"
      + "                                     and u.username = :username"
      + ") or hc.floating_household_location_name  in (SELECT l.name\n"
      + "                                   from plan_assignment pa\n"
      + "                                            inner join organization o on pa.organization_identifier = o.identifier\n"
      + "                                            left join plan_locations pl\n"
      + "                                                      on pl.identifier = pa.plan_locations_identifier\n"
      + "                                            left join location l on l.identifier = pl.location_identifier\n"
      + "                                            left join geographic_level gl\n"
      + "                                                      on gl.identifier = l.geographic_level_identifier\n"
      + "                                            left join plan p on pl.plan_identifier = p.identifier\n"
      + "                                            left join location_hierarchy lh\n"
      + "                                                      on p.hierarchy_identifier = lh.identifier\n"
      + "                                            left join plan_target_type ptt on ptt.plan_identifier = p.identifier\n"
      + "                                            left join geographic_level pgl\n"
      + "                                                      on ptt.geographic_level_identifier = pgl.identifier\n"
      + "                                            left join user_organization uo\n"
      + "                                                      on o.identifier = uo.organization_identifier\n"
      + "                                            left join users u on u.identifier = uo.user_identifier\n"
      + "                                   WHERE gl.name =\n"
      + "                                         lh.node_order[array_position(lh.node_order, pgl.name) - 1]\n"
      + "                                     and u.username = :username"
      + ")"
      + ")\n"
      + "  and hc.server_version > :serverVersion"
      + " LIMIT 10\n",nativeQuery = true)
  List<HdssCompoundHouseholdIndividualProjection> getAllCompoundsForUserAssignmentAndServerVersion(String username, long serverVersion);


  @Query(value = "SELECT DISTINCT cast(hc.id as varchar)                                 as id,\n"
      + "                hc.compound_id                                         as compoundId,\n"
      + "                hc.household_id                                        as householdId,\n"
      + "                hc.individual_id                                       as individualId,\n"
      + "                null                                                as cluster,\n"
      + "                hc.fields ->> 'gender'                                 as gender,\n"
      + "                CAST(hc.fields ->> 'dob' as date)                      as dob,\n"
      + "                hc.server_version                                      as serverVersion,\n"
      + "                cast(hc.structure_id as varchar)                       as structureId,\n"
      + "                hc.name                                                as name,\n"
      + "                cast(hc.floating_location_id as varchar)               as floatingLocationId,\n"
      + "                cast(hc.floating_location_name as varchar)             as floatingLocationName,\n"
      + "                cast(hc.floating_location_geographic_level as varchar) as floatingLocationGeographicLevel,\n"
      + "                cast(hc.floating_household_location_name as varchar)             as floatingHouseholdLocationName\n"
      + "FROM hdss.hdss_compounds hc\n"
      + " LIMIT 10\n",nativeQuery = true)
  List<HdssCompoundHouseholdIndividualProjection> getAllCompoundsForUserAssignmentAndServerVersionV2(String username, long serverVersion);



//  @Query(value = "select count(*) FROM ( SELECT DISTINCT cast(hc.id as varchar)                                 as id,\n"
//      + "                hc.compound_id                                         as compoundId,\n"
//      + "                hc.household_id                                        as householdId,\n"
//      + "                hc.individual_id                                       as individualId,\n"
//      + "                hc.fields ->> 'gender'                                 as gender,\n"
//      + "                CAST(hc.fields ->> 'dob' as date)                      as dob,\n"
//      + "                hc.server_version                                      as serverVersion,\n"
//      + "                cast(hc.structure_id as varchar)                       as structureId,\n"
//      + "                hc.name                                                as name,\n"
//      + "                cast(hc.floating_location_id as varchar)               as getFloatingLocationId,\n"
//      + "                cast(hc.floating_location_name as varchar)             as getFloatingLocationName,\n"
//      + "                cast(hc.floating_location_geographic_level as varchar) as getFloatingLocationGeographicLevel\n"
//      + "\n"
//      + "\n"
//      + "         FROM hdss.hdss_compounds hc\n"
//      + "                  inner join location l on l.name = hc.floating_location_name\n"
//      + "         WHERE hc.floating_location_name is not null\n"
//      + "           and l.identifier in (\n"
//      + "             SELECT l.identifier\n"
//      + "             from plan_assignment pa\n"
//      + "                      inner join organization o on pa.organization_identifier = o.identifier\n"
//      + "                      left join plan_locations pl on pl.identifier = pa.plan_locations_identifier\n"
//      + "                      left join location l on l.identifier = pl.location_identifier\n"
//      + "                      left join geographic_level gl on gl.identifier = l.geographic_level_identifier\n"
//      + "                      left join plan p on pl.plan_identifier = p.identifier\n"
//      + "                      left join location_hierarchy lh on p.hierarchy_identifier = lh.identifier\n"
//      + "                      left join plan_target_type ptt on ptt.plan_identifier = p.identifier\n"
//      + "                      left join geographic_level pgl\n"
//      + "                                on ptt.geographic_level_identifier = pgl.identifier\n"
//      + "                      left join user_organization uo on o.identifier = uo.organization_identifier\n"
//      + "                      left join users u on u.identifier = uo.user_identifier\n"
//      + "             WHERE gl.name = lh.node_order[array_position(lh.node_order, pgl.name) - 1]\n"
//      + "               and u.username = :username\n"
//      + "         )\n"
//      + "        and hc.server_version > :serverVersion\n ) as t",nativeQuery = true)
//  int getCountOfCompoundsForUserAssignmentAndServerVersionAndBatchSize(String username, long serverVersion);

//  @Query(value = "SELECT count(*) from (\n"
//      + "SELECT DISTINCT  cast(hc.id as varchar) as id"
//      + ", hc.compound_id as compoundId"
//      + ",hc.household_id as householdId"
//      + ",hc.individual_id as individualId"
//      + ",  hc.fields->>'gender' as gender"
//      + ", CAST(hc.fields->>'dob' as date)  as dob"
//      + ", hc.server_version as serverVersion"
//      + ", cast(hc.structure_id as varchar) as structureId "
//
//      + ", cast(hc.floating_location_id as varchar) as getFloatingLocationId "
//      + ", cast(hc.floating_location_name as varchar) as getFloatingLocationName "
//      + ", cast(hc.floating_location_geographic_level as varchar) as getFloatingLocationGeographicLevel "
//      + "FROM\n"
//      + "    (SELECT lr.location_identifier as child_location, arr.ancestor\n"
//      + "     from location_relationship lr,\n"
//      + "          unnest(lr.ancestry) with ordinality arr(ancestor, pos)\n"
//      + "    ) as lr\n"
//      + "        left join location lp on lr.ancestor = lp.identifier\n"
//      + "        left join geographic_level pgl on pgl.identifier = lp.geographic_level_identifier\n"
//      + "        left join location lc on lc.identifier = lr.child_location\n"
//      + "        left join geographic_level cgl on cgl.identifier = lc.geographic_level_identifier\n"
//      + "        inner  join hdss.hdss_compounds hc on hc.structure_id = lr.child_location\n"
//      + "WHERE lp.identifier in (\n"
//      + "    SELECT\n"
//      + "        l.identifier\n"
//      + "    from plan_assignment pa\n"
//      + "             inner join organization o on pa.organization_identifier = o.identifier\n"
//      + "             left join plan_locations pl on pl.identifier = pa.plan_locations_identifier\n"
//      + "             left join location l on l.identifier = pl.location_identifier\n"
//      + "             left join geographic_level gl on gl.identifier = l.geographic_level_identifier\n"
//      + "             left join plan p on pl.plan_identifier = p.identifier\n"
//      + "             left join location_hierarchy lh on p.hierarchy_identifier = lh.identifier\n"
//      + "             left join plan_target_type ptt on ptt.plan_identifier = p.identifier\n"
//      + "             left join geographic_level pgl on ptt.geographic_level_identifier = pgl.identifier\n"
//      + "             left join user_organization uo on o.identifier = uo.organization_identifier\n"
//      + "             left join users u on u.identifier = uo.user_identifier\n"
//      + "    WHERE gl.name = lh.node_order[array_position(lh.node_order, pgl.name) - 1]\n"
//      + "      and u.username = :username\n"
//      + ") and  hc.server_version>0\n"
//      + "    )as t",nativeQuery = true)
//  int getTotalCountOfCompoundsForUserAssignmentAndServerVersionAndBatchSize(String username);

  @Query(value = "SELECT count(*) from (SELECT DISTINCT cast(hc.id as varchar)                                 as id,\n"
      + "                hc.compound_id                                         as compoundId,\n"
      + "                hc.household_id                                        as householdId,\n"
      + "                hc.individual_id                                       as individualId,\n"
      + "                lp.name                                                as cluster,\n"
      + "                hc.fields ->> 'gender'                                 as gender,\n"
      + "                CAST(hc.fields ->> 'dob' as date)                      as dob,\n"
      + "                hc.server_version                                      as serverVersion,\n"
      + "                cast(hc.structure_id as varchar)                       as structureId,\n"
      + "                hc.name                                                as name,\n"
      + "                cast(hc.floating_location_id as varchar)               as getFloatingLocationId,\n"
      + "                cast(hc.floating_location_name as varchar)             as getFloatingLocationName,\n"
      + "                cast(hc.floating_location_geographic_level as varchar) as getFloatingLocationGeographicLevel\n"
      + "FROM hdss.hdss_compounds hc\n"
      + "         LEFT JOIN\n"
      + "\n"
      + "     (SELECT lr.location_identifier as child_location, arr.ancestor\n"
      + "      from location_relationship lr,\n"
      + "           unnest(lr.ancestry) with ordinality arr(ancestor, pos)\n"
      + "     ) as lr on lr.child_location = hc.structure_id\n"
      + "         left join location lp on lr.ancestor = lp.identifier\n"
      + "\n"
      + "WHERE (lr.ancestor in (\n"
      + "    SELECT l.identifier\n"
      + "    from plan_assignment pa\n"
      + "             inner join organization o on pa.organization_identifier = o.identifier\n"
      + "             left join plan_locations pl on pl.identifier = pa.plan_locations_identifier\n"
      + "             left join location l on l.identifier = pl.location_identifier\n"
      + "             left join geographic_level gl on gl.identifier = l.geographic_level_identifier\n"
      + "             left join plan p on pl.plan_identifier = p.identifier\n"
      + "             left join location_hierarchy lh on p.hierarchy_identifier = lh.identifier\n"
      + "             left join plan_target_type ptt on ptt.plan_identifier = p.identifier\n"
      + "             left join geographic_level pgl on ptt.geographic_level_identifier = pgl.identifier\n"
      + "             left join user_organization uo on o.identifier = uo.organization_identifier\n"
      + "             left join users u on u.identifier = uo.user_identifier\n"
      + "    WHERE gl.name = lh.node_order[array_position(lh.node_order, pgl.name) - 1]\n"
      + "      and u.username = :username\n"
      + ") or hc.floating_location_name in (SELECT l.name\n"
      + "                                   from plan_assignment pa\n"
      + "                                            inner join organization o on pa.organization_identifier = o.identifier\n"
      + "                                            left join plan_locations pl\n"
      + "                                                      on pl.identifier = pa.plan_locations_identifier\n"
      + "                                            left join location l on l.identifier = pl.location_identifier\n"
      + "                                            left join geographic_level gl\n"
      + "                                                      on gl.identifier = l.geographic_level_identifier\n"
      + "                                            left join plan p on pl.plan_identifier = p.identifier\n"
      + "                                            left join location_hierarchy lh\n"
      + "                                                      on p.hierarchy_identifier = lh.identifier\n"
      + "                                            left join plan_target_type ptt on ptt.plan_identifier = p.identifier\n"
      + "                                            left join geographic_level pgl\n"
      + "                                                      on ptt.geographic_level_identifier = pgl.identifier\n"
      + "                                            left join user_organization uo\n"
      + "                                                      on o.identifier = uo.organization_identifier\n"
      + "                                            left join users u on u.identifier = uo.user_identifier\n"
      + "                                   WHERE gl.name =\n"
      + "                                         lh.node_order[array_position(lh.node_order, pgl.name) - 1]\n"
      + "                                     and u.username = :username"
      + ") or hc.floating_household_location_name in (SELECT l.name\n"
      + "                                   from plan_assignment pa\n"
      + "                                            inner join organization o on pa.organization_identifier = o.identifier\n"
      + "                                            left join plan_locations pl\n"
      + "                                                      on pl.identifier = pa.plan_locations_identifier\n"
      + "                                            left join location l on l.identifier = pl.location_identifier\n"
      + "                                            left join geographic_level gl\n"
      + "                                                      on gl.identifier = l.geographic_level_identifier\n"
      + "                                            left join plan p on pl.plan_identifier = p.identifier\n"
      + "                                            left join location_hierarchy lh\n"
      + "                                                      on p.hierarchy_identifier = lh.identifier\n"
      + "                                            left join plan_target_type ptt on ptt.plan_identifier = p.identifier\n"
      + "                                            left join geographic_level pgl\n"
      + "                                                      on ptt.geographic_level_identifier = pgl.identifier\n"
      + "                                            left join user_organization uo\n"
      + "                                                      on o.identifier = uo.organization_identifier\n"
      + "                                            left join users u on u.identifier = uo.user_identifier\n"
      + "                                   WHERE gl.name =\n"
      + "                                         lh.node_order[array_position(lh.node_order, pgl.name) - 1]\n"
      + "                                     and u.username = :username"
      + ")"
      + " )) as t ",nativeQuery = true)
  int getTotalCountOfCompoundsForUserAssignmentAndServerVersionAndBatchSize(String username);

  @Query(value = "SELECT\n"
      + "    distinct u.email\n"
      + "from plan_assignment pa\n"
      + "         inner join organization o on pa.organization_identifier = o.identifier\n"
      + "         left join plan_locations pl on pl.identifier = pa.plan_locations_identifier\n"
      + "         left join location l on l.identifier = pl.location_identifier\n"
      + "         left join geographic_level gl on gl.identifier = l.geographic_level_identifier\n"
      + "         left join plan p on pl.plan_identifier = p.identifier\n"
      + "         left join location_hierarchy lh on p.hierarchy_identifier = lh.identifier\n"
      + "         left join plan_target_type ptt on ptt.plan_identifier = p.identifier\n"
      + "         left join geographic_level pgl on ptt.geographic_level_identifier = pgl.identifier\n"
      + "         left join user_organization uo on o.identifier = uo.organization_identifier\n"
      + "         left join users u on u.identifier = uo.user_identifier\n"
      + "inner join (\n"
      + "    SELECT lp.identifier,hc.compound_id\n"
      + "    FROM (SELECT lr.location_identifier as child_location, arr.ancestor\n"
      + "          from location_relationship lr,\n"
      + "               unnest(lr.ancestry) with ordinality arr(ancestor, pos)\n"
      + "         ) as lr\n"
      + "             left join location lp on lr.ancestor = lp.identifier\n"
      + "             left join geographic_level pgl on pgl.identifier = lp.geographic_level_identifier\n"
      + "             left join location lc on lc.identifier = lr.child_location\n"
      + "             left join geographic_level cgl on cgl.identifier = lc.geographic_level_identifier\n"
      + "             inner join hdss.hdss_compounds hc on hc.structure_id = lr.child_location\n"
      + "    WHERE hc.compound_id = :compoundId\n"
      + ") hl on hl.identifier = l.identifier\n"
      + "WHERE p.identifier= :planIdentifier",nativeQuery = true)
  List<String> getUserEmailsByCompoundIdAndPlan(String compoundId, UUID planIdentifier);

  @Query(value = "SELECT max(hc.server_version)  from hdss.hdss_compounds hc",nativeQuery = true)
  long getMaxServerVersion();

  @Query("SELECT DISTINCT  h.householdId FROM HdssCompounds h WHERE h.compoundId = :compoundId")
  List<String> getDistinctHouseholdsByCompoundId(List<String> compoundId);

  @Query("SELECT DISTINCT  h.householdId FROM HdssCompounds h WHERE h.compoundId = :compoundId and h.structureId IS NOT NULL")
  List<String> getDistinctHouseholdsByCompoundIdWithStructure(List<String> compoundId);

  @Query("SELECT DISTINCT  h.structureId FROM HdssCompounds h WHERE h.compoundId in :compoundId")
  List<UUID> getDistinctStructuresByCompoundId(List<String> compoundId);

  @Query("SELECT DISTINCT  h.structureId FROM HdssCompounds h WHERE h.compoundId in :compoundId and h.structureId IS NOT NULL")
  List<UUID> getDistinctStructuresByCompoundIdExcludingNullStructures(List<String> compoundId);

  @Query(value = "SELECT h.structureId  FROM HdssCompounds h WHERE h.individualId = :individualId ")
  UUID getStructureByIndividualId(String individualId);

  @Query(value = "SELECT h.householdId  FROM HdssCompounds h WHERE h.individualId = :individualId")
  String getHouseHoldByIndividualId(String individualId);

  @Query(value = "SELECT DISTINCT h.compoundId  FROM HdssCompounds h WHERE h.householdId = :householdId ")
  List<String> getDistinctCompoundsByHouseholdId(String householdId);

  @Query(value = "SELECT DISTINCT cast(hc.id as varchar) as id, hc.individual_id as individualId"
      + ",CAST(hc.fields->>'dob' as date) as dob,fields->>'gender' as gender from  hdss.hdss_compounds hc WHERE hc.household_id = :householdId", nativeQuery = true)
  List<HdssIndividualProjection> getAllIndividualsByHouseholdId(String householdId);

  @Query(value = "SELECT DISTINCT cast(hc.id as varchar) as id, hc.individual_id as individualId"
      + ",CAST(hc.fields->>'dob' as date) as dob,fields->>'gender' as gender, hc.name as indName from  hdss.hdss_compounds hc WHERE hc.individual_id = :individualId", nativeQuery = true)
  HdssIndividualProjection getIndividualByIndividualId(String individualId);

  @Query(value = "SELECT DISTINCT cast(hc.id as varchar) as id, hc.individual_id as individualId"
      + ",CAST(hc.fields->>'dob' as date) as dob,fields->>'gender' as gender from  hdss.hdss_compounds hc WHERE hc.compound_id in :compoundId", nativeQuery = true)
  List<HdssIndividualProjection> getAllIndividualsInCompoundId(List<String> compoundId);

  @Query(value = "SELECT DISTINCT cast(hc.id as varchar) as id, hc.individual_id as individualId, hc.household_id as householdId"
      + ",CAST(hc.fields->>'dob' as date) as dob,fields->>'gender' as gender from  hdss.hdss_compounds hc WHERE hc.compound_id in :compoundId AND "
      + "hc.structure_id IS NOT NULL", nativeQuery = true)
  List<HdssIndividualProjection> getAllIndividualsInCompoundIdWithStructure(List<String> compoundId);

  List<HdssCompounds> findAllByIndividualIdIn(List<String> individualIds);
}
