package com.revealprecision.revealserver.constants;

public interface KafkaConstants {

  String PLAN_UPDATE = "PLAN_UPDATE";
  String TASK = "TASK";
  String PLAN_LOCATION_ASSIGNED = "PLAN_LOCATION_ASSIGNED";
  String LOCATIONS_IMPORTED = "LOCATIONS_IMPORTED";
  String LOCATION_METADATA_UPDATE = "LOCATION_METADATA_UPDATE";
  String PERSON_METADATA_UPDATE = "PERSON_METADATA_UPDATE";
  String TASK_CANDIDATE = "TASK_CANDIDATE";
  String TASK_CANDIDATE_GENERATE = "TASK_CANDIDATE_GENERATE";
  String TASK_CANDIDATE_REACTIVATE = "TASK_CANDIDATE_REACTIVATE";
  String TASK_CANDIDATE_CANCEL = "TASK_CANDIDATE_CANCEL";
  String EVENT_CONSUMPTION = "EVENT_CONSUMPTION";
  String FORM_EVENT_CONSUMPTION = "FORM_EVENT_CONSUMPTION";
  String LOCATION_SUPERVISOR_CDD = "LOCATION_SUPERVISOR_CDD";
  String USER_DATA = "USER_DATA";
  String USER_PERFORMANCE_DATA = "USER_PERFORMANCE_DATA";
  String USER_PARENT_CHILD = "USER_PARENT_CHILD";
  String FORM_SUBMISSIONS = "FORM_SUBMISSIONS";
  String FORM_SUBMISSIONS_PARENT = "FORM_SUBMISSIONS_PARENT";
  String EVENT_TRACKER = "EVENT_TRACKER";
  String EVENT_AGGREGATION_LOCATION = "EVENT_AGGREGATION_LOCATION";

}
