package com.revealprecision.revealserver.constants;

public interface KafkaConstants {

  String PLAN_UPDATE = "PLAN_UPDATE";
  String TASK = "TASK";
  String PLAN_LOCATION_ASSIGNED = "PLAN_LOCATION_ASSIGNED";
  String PLAN_LOCATION_ASSIGNED_STREAM = "PLAN_LOCATION_ASSIGNED_STREAM";
  String LOCATIONS_IMPORTED = "LOCATIONS_IMPORTED";
  String LOCATION_METADATA_UPDATE = "LOCATION_METADATA_UPDATE";
  String PERSON_METADATA_UPDATE = "PERSON_METADATA_UPDATE";
  String tableOfOperationalAreaHierarchiesTOPIC = "tableOfOperationalAreaHierarchiesTOPIC";
  String TASK_CANDIDATE = "TASK_CANDIDATE";
  String EVENT_CONSUMPTION = "EVENT_CONSUMPTION";
  String FORM_EVENT_CONSUMPTION = "FORM_EVENT_CONSUMPTION";
  String LOCATION_SUPERVISOR_CDD = "LOCATION_SUPERVISOR_CDD";
  String METADATA_AGGREGATE = "METADATA_AGGREGATE";
  String USER_DATA = "USER_DATA";
  String USER_PERFORMANCE_DATA = "USER_PERFORMANCE_DATA";
  String USER_PARENT_CHILD = "USER_PARENT_CHILD";
  String METADATA_COUNT_AGGREGATE = "METADATA_COUNT_AGGREGATE";
  String METADATA_MINMAX_AGGREGATE = "METADATA_MINMAX_AGGREGATE";
  String FORM_SUBMISSIONS = "FORM_SUBMISSIONS";

}
