package com.revealprecision.revealserver.enums;

public enum ReportTypeEnum {

    MDA_FULL_COVERAGE,
    MDA_LITE_COVERAGE,
    MDA_FULL_COVERAGE_OPERATIONAL_AREA_LEVEL,
    IRS_FULL_COVERAGE,
    IRS_LITE_COVERAGE,
    IRS_LITE_COVERAGE_OPERATIONAL_AREA_LEVEL,
    SURVEY,
    LSM_HOUSEHOLD_SURVEY,
    LSM_HABITAT_SURVEY,
    ONCHOCERCIASIS_SURVEY
}
