ALTER TABLE setting
ALTER COLUMN type TYPE VARCHAR(255),
ALTER COLUMN key TYPE VARCHAR(255),
ALTER COLUMN value TYPE VARCHAR(255),
ALTER COLUMN label TYPE VARCHAR(255),
ALTER COLUMN description TYPE VARCHAR(255);

ALTER TABLE setting_aud
ALTER COLUMN type TYPE VARCHAR(255),
ALTER COLUMN key TYPE VARCHAR(255),
ALTER COLUMN value TYPE VARCHAR(255),
ALTER COLUMN label TYPE VARCHAR(255),
ALTER COLUMN description TYPE VARCHAR(255);