
ALTER TABLE IF EXISTS  "group"
    ADD COLUMN created_by VARCHAR(36) NOT NULL,
    ADD COLUMN    created_datetime TIMESTAMP WITH TIME ZONE NOT NULL,
    ADD COLUMN   modified_by VARCHAR(36) NOT NULL,
    ADD COLUMN    modified_datetime TIMESTAMP WITH TIME ZONE NOT NULL;

ALTER TABLE IF EXISTS  person
    ADD COLUMN created_by VARCHAR(36) NOT NULL,
    ADD COLUMN    created_datetime TIMESTAMP WITH TIME ZONE NOT NULL,
    ADD COLUMN   modified_by VARCHAR(36) NOT NULL,
    ADD COLUMN    modified_datetime TIMESTAMP WITH TIME ZONE NOT NULL;

