# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Reveal Server test and build

on:
  push:
    branches:
      - '/refs/heads/*'
      - '!main'
  pull_request:
    branches:
      - '/refs/heads/*'
      - '!main'

jobs:
  dependancy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew dependencyCheckAnalyze --info

  code-quality:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        SONAR_SECRET: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew --stacktrace --warning-mode all sonarqube -Dsonar.login="$SONAR_SECRET" -Dsonar.host.url=https://sonar-ops.akros.online  -Dsonar.dependencyCheck.htmlReportPath=build/reports/dependency-check-report.html

  build:

    runs-on: ubuntu-latest
    needs: [dependancy, code-quality]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build